name: Test virt-install workflow dispatch
on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '10 3 * * 1'

jobs:
  test-dispatch:
    name: Dispatch
    runs-on: ubuntu-slim
    permissions:
      actions: write
    timeout-minutes: 5
    if: github.event_name != 'schedule' || github.repository == 'adelton/virt-install'
    steps:
      - run: |
          jq -n -f /dev/stdin <<'EOS' \
          | tee /dev/stderr \
          | curl -sS --fail-with-body -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H 'Content-Type: application/json' \
            -d '@-' \
            "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/workflows/virt-install.yaml/dispatches"
          {
            "ref": ( if $ENV.GITHUB_HEAD_REF != "" then "refs/heads/" + $ENV.GITHUB_HEAD_REF else $ENV.GITHUB_REF end ),
            "inputs": {
              "disk-url": "https://repo.almalinux.org/almalinux/10/cloud/x86_64/images/AlmaLinux-10-GenericCloud-latest.x86_64.qcow2",
              "osinfo": "almalinux10",
              "command": "cat /etc/os-release"
            }
          }
          EOS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
